example/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("locnus.urls", namespace="locnus")),
]

locnus/locnus/urls.py
# from apps.core import views
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

locnus/urls.py
from django.urls import path

from . import views

app_name = "client"

urlpatterns = [
    # home
    path("", views.home, name="home"),
    # server
    path("server-list/", views.server_list, name="server-list"),
    path("server-create/", views.get_create_server, name="get-create-server"),
    path("client-post-create/", views.post_create_server, name="post-create-server"),
    path("delete-server/<int:server_pk>", views.delete_server, name="delete-server"),
    # account
    path("account-list/<int:server_pk>", views.get_account_list, name="account-list"),
    path("account-create/", views.get_create_account, name="get-create-account"),
    path("account-post-create/", views.post_create_account, name="post-create-account"),
    path("personal-timeline/<int:account_pk>", views.get_personal_timeline, name="personal-timeline"),
    # timeline
    path("public-timeline/<int:server_pk>", views.get_public_timeline, name="public-timeline"),
    # toot
    path("toot-get-create/", views.get_create_toot, name="get-create-toot"),
    path("toot-post-create/", views.post_create_toot, name="post-create-toot"),
    # htmx test
    path("htmx-test/", views.htmx_test, name="htmx-test"),
]

locnus/apps/core/models.py
from django.db import models


class Client(models.Model):
    api_base_url = models.URLField(verbose_name="API Base URL", unique=True)
    name = models.CharField(max_length=100)
    remote_id = models.CharField(max_length=100)
    secret = models.CharField(max_length=100)

    def __str__(self):
        return self.api_base_url


class ClientUser(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    username = models.CharField(max_length=100)
    access_token = models.CharField(max_length=100)

locnus/models.py
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models
from mastodon import Mastodon


class Client(models.Model):
    name = models.CharField(max_length=100, default="pytooterapp")
    remote_id = models.CharField(max_length=100)
    secret = models.CharField(max_length=100)

    def __str__(self):
        return f"<{self.name}>"

    def set_remote_id_and_secret(self, api_base_url):
        self.remote_id, self.secret = Mastodon.create_app(self.name, api_base_url=api_base_url)

    @classmethod
    def from_api_base_url(cls, api_base_url, name=None):
        client = cls()
        if name is not None:
            client.name = name
        client.set_remote_id_and_secret(api_base_url)
        return client


class Server(models.Model):
    api_base_url = models.URLField(verbose_name="API Base URL", unique=True)
    client = models.OneToOneField(Client, on_delete=models.SET_NULL, null=True, blank=True, related_name="server")

    def __str__(self):
        return self.api_base_url

    def get_access_token(self, username, password):
        if self.client is None:
            self.client = Client.from_api_base_url(self.api_base_url)

        mastodon = Mastodon(
            client_id=self.client.remote_id,
            client_secret=self.client.secret,
            api_base_url=self.api_base_url,
        )
        return mastodon.log_in(username, password)

    def public_timeline(self):
        mastodon = Mastodon(api_base_url=self.api_base_url)
        return mastodon.timeline_public()

    def timeline_public(self):
        return Timeline.objects.public().filter(server=self)

    def timeline_local(self):
        return Timeline.objects.local().filter(server=self)


class Account(models.Model):
    server = models.ForeignKey(Server, on_delete=models.CASCADE, related_name="accounts")
    username = models.CharField(max_length=100)
    access_token = models.CharField(max_length=100)

    def __str__(self):
        return f"<{self.username}, {self.server}>"

    def personal_timeline(self):
        mastodon = Mastodon(
            access_token=self.access_token,
            api_base_url=self.server.api_base_url,
        )
        return mastodon.timeline_home()

    def timeline_home(self):
        timeline_qs = Timeline.objects.filter(tag=Timeline.Tag.HOME, account=self).order_by("-status__created_at")
        toots = [timeline.status for timeline in timeline_qs]
        return toots

    def toot(self, content):
        mastodon = Mastodon(
            access_token=self.access_token,
            api_base_url=self.server.api_base_url,
        )
        response = mastodon.toot(content)
        return response

    def add_toot_to_home_timeline(self, toot):
        status = Status(pk=toot["id"], created_at=toot["created_at"], data=toot)
        status.save()
        item = Timeline(account=self, status=status, tag=Timeline.Tag.HOME, server=self.server)
        item.save()
        return item


class TimelineManager(models.Manager):
    def public(self):
        return self.filter(tag=Timeline.Tag.PUBLIC)

    def local(self):
        return self.filter(tag=Timeline.Tag.LOCAL)


class Timeline(models.Model):
    status = models.ForeignKey("Status", on_delete=models.CASCADE, related_name="timelines")
    account = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True, blank=True)
    server = models.ForeignKey(Server, on_delete=models.CASCADE)

    objects = TimelineManager()

    class Tag(models.IntegerChoices):
        PUBLIC = 1
        LOCAL = 2
        HOME = 3

    tag = models.IntegerField(choices=Tag.choices)


class Status(models.Model):
    id = models.BigIntegerField(primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)
    data = models.JSONField(encoder=DjangoJSONEncoder)
    timeline = models.ManyToManyField(Server, through=Timeline)

    @property
    def content(self):
        return self.data.get("content")

    @property
    def display_name(self):
        return self.data.get("account", {}).get("display_name")

locnus/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.forms import CharField, Form, ModelForm, PasswordInput
from mastodon import MastodonIllegalArgumentError

from .models import Account, Server


class ServerForm(ModelForm):
    class Meta:
        model = Server
        fields = ["api_base_url"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit("submit", "Submit"))


class AccountForm(ModelForm):
    password = CharField(widget=PasswordInput())

    class Meta:
        model = Account
        fields = ["server", "username"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit("submit", "Submit"))

    def full_clean(self):
        super().full_clean()
        try:
            self.instance.access_token = self.instance.server.get_access_token(
                self.cleaned_data["username"], self.cleaned_data["password"]
            )
        except MastodonIllegalArgumentError:
            self.add_error("password", "Invalid username or password")


class TootForm(Form):
    content = CharField()

    class Meta:
        fields = ["content"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit("submit", "Submit"))

locnus/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_GET, require_http_methods, require_POST

from .forms import AccountForm, ServerForm, TootForm
from .models import Account, Server


@require_GET
def home(request):
    toots = []
    account = Account.objects.first()
    # print(request.session.get("seen_toots", {}))
    if account is not None:
        toots = account.timeline_home()
        print("toots: ", toots)
        try:
            toots = [t for t in toots if str(t.id) not in request.session["seen_toots"]]
        except KeyError:
            request.session["seen_toots"] = {}
    if request.htmx:
        print("toots: ", toots)
        table_rows = []
        for toot in toots:
            row = f"<tr><th>{toot.id}</th><td>{toot.display_name}</td><td>{toot.content}</td></tr>"
            table_rows.append(row)
            request.session["seen_toots"][toot.id] = True
            request.session.save()
        content = "\n".join(table_rows).encode("utf-8")
        return HttpResponse(content=content, content_type="text/html")
        # return HttpResponse(status=204)
    else:
        request.session["seen_toots"] = {}
        for toot in toots:
            request.session["seen_toots"][toot.id] = True
        return render(request, "home.html", context={"toots": toots})


@require_GET
def server_list(request):
    servers = Server.objects.all()
    return render(request, "server_list.html", context={"servers": servers})


@require_POST
def post_create_server(request):
    form = ServerForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect("locnus:server-list")
    else:
        return render(request, "create_server.html", context={"form": form})


@require_GET
def get_create_server(request):
    form = ServerForm()
    return render(request, "create_server.html", context={"form": form})


@require_http_methods(["DELETE"])
def delete_server(request, server_pk):
    print("delete_server: ", server_pk)
    server = get_object_or_404(Server, pk=server_pk)
    server.delete()
    if request.htmx:
        return HttpResponse(status=200, content="")
    else:
        return redirect("locnus:server-list")


@require_GET
def get_account_list(request, server_pk):
    server = Server.objects.get(pk=server_pk)
    accounts = server.accounts.all()
    return render(request, "account_list.html", context={"server": server, "accounts": accounts})


@require_GET
def get_create_account(request):
    form = AccountForm()
    return render(request, "create_account.html", context={"form": form})


@require_POST
def post_create_account(request):
    form = AccountForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect("locnus:account-list", server_pk=form.instance.server.pk)
    else:
        return render(request, "create_account.html", context={"form": form})


@require_GET
def get_personal_timeline(request, account_pk):
    account = Account.objects.get(pk=account_pk)
    toots = account.personal_timeline()
    return render(request, "timeline.html", context={"account": account, "toots": toots})


@require_GET
def get_public_timeline(request, server_pk):
    server = get_object_or_404(Server, pk=server_pk)
    toots = server.public_timeline()
    return render(request, "timeline.html", context={"server": server, "toots": toots})


@require_GET
def get_create_toot(request):
    form = TootForm()
    return render(request, "create_toot.html", context={"form": form})


@require_POST
def post_create_toot(request):
    account = Account.objects.first()
    form = TootForm(request.POST)
    if form.is_valid():
        account.toot(form.cleaned_data["content"])
        return redirect("locnus:home")
    else:
        return render(request, "create_toot.html", context={"form": form})


def htmx_test(request):
    button = """
        <button hx-post="/htmx-test/"
            hx-trigger="click" hx-target="this"
            hx-swap="outerHTML" class="btn btn-secondary"
          >
          Click Me!
          </button>
    """
    return HttpResponse(content=button.encode("utf8"), content_type="text/html")

locnus/templates/account_detail.html
{% extends "_base.html" %}

{% block main %}
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1 mt-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">List of Users for this server.</h5>
              <p class="card-text">
                Click to add a new Account!
              </p>
              <a href='{% url "locnus:get-create-account" %}'>
                <button type="button" class="btn btn-primary">Add Account</button>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1 mt-4">
          {% if toots %}
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">ID</th>
                  <th scope="col">Content</th>
                </tr>
              </thead>
              <tbody>
                {% for toot in toots %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ toot.id }}</td>
                    <td>{{ toot.content }}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

locnus/templates/account_list.html
{% extends "_base.html" %}

{% block main %}
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1 mt-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">List of Users for this server.</h5>
              <p class="card-text">
                Click to add a new Account!
              </p>
              <a href='{% url "locnus:get-create-account" %}'>
                <button type="button" class="btn btn-primary">Add Account</button>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1 mt-4">
          {% if accounts %}
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Username</th>
                  <th scope="col">Your Feed</th>
                </tr>
              </thead>
              <tbody>
                {% for account in accounts %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ account.username }}</td>
                    <td><a href='{% url "locnus:personal-timeline" account_pk=account.pk %}'>
                      <button type="button" class="btn btn-light">Toots</button>
                    </a></td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

locnus/templates/client_list.html
{% extends "_base.html" %}

{% block main %}
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1 mt-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">List of registered ActivityPub clients.</h5>
              <p class="card-text">
                Click to add a new ActivityPub client!
              </p>
              <a href='{% url "client:get-create-client" %}'>
                <button type="button" class="btn btn-primary">Add Client</button>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1 mt-4">
          {% if clients %}
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Base API Url</th>
                  <th scope="col">Name</th>
                  <th scope="col">Public</th>
                  <th scope="col">Personal</th>
                </tr>
              </thead>
              <tbody>
                {% for client in clients %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href='{% url "client:client-update" %}'>{{ client.api_base_url }}</a></td>
                    <td>{{ client.name }}</td>
                    <td><a href='{% url "client:timeline" client_pk=client.pk %}'>
                      <button type="button" class="btn btn-light">Timeline</button>
                    </a></td>
                    <td><a href='{% url "client:login-list" client_pk=client.pk %}'>
                      <button type="button" class="btn btn-light">Logins</button>
                    </a></td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

locnus/templates/create_client.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}

{% block main %}
  <div class="container">
    <div class="row">
      <div class="col-md-10 offset-md-1 mt-4">
        <form method="post" action='{% url "client:post-create-client" %}'>
          {% csrf_token %}
          {% crispy form %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

locnus/templates/create_login.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}

{% block main %}
  <div class="container">
    <div class="row">
      <div class="col-md-10 offset-md-1 mt-4">
        <form method="post" action='{% url "locnus:post-create-login" %}'>
          {% csrf_token %}
          {% crispy form %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

locnus/templates/create_server.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}

{% block main %}
  <div class="container">
    <div class="row">
      <div class="col-md-10 offset-md-1 mt-4">
        <form method="post" action='{% url "locnus:post-create-server" %}'>
          {% csrf_token %}
          {% crispy form %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

locnus/templates/home.html
{% extends "_base.html" %}

{% block main %}
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1 mt-4">
          {% include "./timeline_partial.html" with toots=toots %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

locnus/templates/index.html
{% extends "_base.html" %}

{% block main %}
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1 mt-4">
          {% include "./timeline_partial.html" with toots=toots %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

locnus/templates/login_detail.html
{% extends "_base.html" %}

{% block main %}
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1 mt-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">List of Users for this server.</h5>
              <p class="card-text">
                Click to add a new Login!
              </p>
              <a href='{% url "locnus:get-create-login" %}'>
                <button type="button" class="btn btn-primary">Add Login</button>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1 mt-4">
          {% if toots %}
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">ID</th>
                  <th scope="col">Content</th>
                </tr>
              </thead>
              <tbody>
                {% for toot in toots %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ toot.id }}</td>
                    <td>{{ toot.content }}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

locnus/templates/login_list.html
{% extends "_base.html" %}

{% block main %}
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1 mt-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">List of Users for this server.</h5>
              <p class="card-text">
                Click to add a new Login!
              </p>
              <a href='{% url "locnus:get-create-login" %}'>
                <button type="button" class="btn btn-primary">Add Login</button>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1 mt-4">
          {% if logins %}
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Username</th>
                  <th scope="col">Your Feed</th>
                </tr>
              </thead>
              <tbody>
                {% for login in logins %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ login.username }}</td>
                    <td><a href='{% url "locnus:personal-timeline" login_pk=login.pk %}'>
                      <button type="button" class="btn btn-light">Toots</button>
                    </a></td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

locnus/templates/server_list.html
{% extends "_base.html" %}

{% block main %}
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1 mt-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">List of registered ActivityPub servers.</h5>
              <p class="card-text">
                Click to add a new ActivityPub server!
              </p>
              <a href='{% url "locnus:get-create-server" %}'>
                <button type="button" class="btn btn-primary">Add Server</button>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1 mt-4">
          {% if servers %}
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Base API Url</th>
                  <th scope="col">Name</th>
                  <th scope="col">Public</th>
                  <th scope="col">Private</th>
                  <th scope="col">Delete</th>
                </tr>
              </thead>
              <tbody hx-confirm="Are you sure?" hx-target="closest tr" hx-swap="outerHTML swap:1s">
                {% for server in servers %}
                  <tr >
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href="{{ server.api_base_url }}">{{ server.api_base_url }}</a></td>
                    <td>{{ server.name }}</td>
                    <td><a href='{% url "locnus:public-timeline" server_pk=server.pk %}'>
                      <button type="button" class="btn btn-light">Timeline</button>
                    </a></td>
                    <td><a href='{% url "locnus:account-list" server_pk=server.pk %}'>
                      <button type="button" class="btn btn-light">Accounts</button>
                    </a></td>
                    <td>
                      <button hx-delete='{% url "locnus:delete-server" server_pk=server.pk %}'
                              type="button" class="btn btn-danger">Delete</button>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

locnus/templates/timeline_partial.html
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-10 offset-md-1 mt-4">
        {% if toots %}
          <p hx-get="{% url 'locnus:home' %}"
             hx-trigger="every 5s"
             hx-target="#toots-start"
             hx-swap="afterbegin"
          >
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">User</th>
                  <th scope="col">Content</th>
                </tr>
              </thead>
              <tbody id="toots-start">
                {% for toot in toots %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ toot.display_name }}</td>
                    <td>{{ toot.content | safe}}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">No toots found!</h5>
              <p class="card-text">
                Click to add a new ActivityPub account!
              </p>
              <a href='{% url "locnus:get-create-account" %}'>
                <button type="button" class="btn btn-primary">Add Account</button>
              </a>
            </div>
        {% endif %}
      </div>
    </div>
  </div>
</section>